export interface Language {
  code: string
  name: string
  countryCode?: string // ISO 3166-1 alpha-2 country code for flag display
}

export const ISO_639_1_LANGUAGES: Language[] = [
  { code: 'auto', name: 'Auto-detect' },
  { code: 'aa', name: 'Afar', countryCode: 'ET' },
  { code: 'ab', name: 'Abkhazian', countryCode: 'GE' },
  { code: 'ae', name: 'Avestan' },
  { code: 'af', name: 'Afrikaans', countryCode: 'ZA' },
  { code: 'ak', name: 'Akan', countryCode: 'GH' },
  { code: 'am', name: 'Amharic', countryCode: 'ET' },
  { code: 'an', name: 'Aragonese', countryCode: 'ES' },
  { code: 'ar', name: 'Arabic', countryCode: 'SA' },
  { code: 'as', name: 'Assamese', countryCode: 'IN' },
  { code: 'av', name: 'Avaric', countryCode: 'RU' },
  { code: 'ay', name: 'Aymara', countryCode: 'BO' },
  { code: 'az', name: 'Azerbaijani', countryCode: 'AZ' },
  { code: 'ba', name: 'Bashkir', countryCode: 'RU' },
  { code: 'be', name: 'Belarusian', countryCode: 'BY' },
  { code: 'bg', name: 'Bulgarian', countryCode: 'BG' },
  { code: 'bh', name: 'Bihari languages', countryCode: 'IN' },
  { code: 'bi', name: 'Bislama', countryCode: 'VU' },
  { code: 'bm', name: 'Bambara', countryCode: 'ML' },
  { code: 'bn', name: 'Bengali', countryCode: 'BD' },
  { code: 'bo', name: 'Tibetan', countryCode: 'CN' },
  { code: 'br', name: 'Breton', countryCode: 'FR' },
  { code: 'bs', name: 'Bosnian', countryCode: 'BA' },
  { code: 'ca', name: 'Catalan', countryCode: 'ES' },
  { code: 'ce', name: 'Chechen', countryCode: 'RU' },
  { code: 'ch', name: 'Chamorro', countryCode: 'GU' },
  { code: 'co', name: 'Corsican', countryCode: 'FR' },
  { code: 'cr', name: 'Cree', countryCode: 'CA' },
  { code: 'cs', name: 'Czech', countryCode: 'CZ' },
  { code: 'cu', name: 'Church Slavic' },
  { code: 'cv', name: 'Chuvash', countryCode: 'RU' },
  { code: 'cy', name: 'Welsh', countryCode: 'GB' },
  { code: 'da', name: 'Danish', countryCode: 'DK' },
  { code: 'de', name: 'German', countryCode: 'DE' },
  { code: 'dv', name: 'Divehi', countryCode: 'MV' },
  { code: 'dz', name: 'Dzongkha', countryCode: 'BT' },
  { code: 'ee', name: 'Ewe', countryCode: 'GH' },
  { code: 'el', name: 'Greek', countryCode: 'GR' },
  { code: 'en', name: 'English', countryCode: 'US' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'es', name: 'Spanish', countryCode: 'ES' },
  { code: 'et', name: 'Estonian', countryCode: 'EE' },
  { code: 'eu', name: 'Basque', countryCode: 'ES' },
  { code: 'fa', name: 'Persian', countryCode: 'IR' },
  { code: 'ff', name: 'Fulah', countryCode: 'SN' },
  { code: 'fi', name: 'Finnish', countryCode: 'FI' },
  { code: 'fj', name: 'Fijian', countryCode: 'FJ' },
  { code: 'fo', name: 'Faroese', countryCode: 'FO' },
  { code: 'fr', name: 'French', countryCode: 'FR' },
  { code: 'fy', name: 'Western Frisian', countryCode: 'NL' },
  { code: 'ga', name: 'Irish', countryCode: 'IE' },
  { code: 'gd', name: 'Scottish Gaelic', countryCode: 'GB' },
  { code: 'gl', name: 'Galician', countryCode: 'ES' },
  { code: 'gn', name: 'Guaraní', countryCode: 'PY' },
  { code: 'gu', name: 'Gujarati', countryCode: 'IN' },
  { code: 'gv', name: 'Manx', countryCode: 'IM' },
  { code: 'ha', name: 'Hausa', countryCode: 'NG' },
  { code: 'he', name: 'Hebrew', countryCode: 'IL' },
  { code: 'hi', name: 'Hindi', countryCode: 'IN' },
  { code: 'ho', name: 'Hiri Motu', countryCode: 'PG' },
  { code: 'hr', name: 'Croatian', countryCode: 'HR' },
  { code: 'ht', name: 'Haitian Creole', countryCode: 'HT' },
  { code: 'hu', name: 'Hungarian', countryCode: 'HU' },
  { code: 'hy', name: 'Armenian', countryCode: 'AM' },
  { code: 'hz', name: 'Herero', countryCode: 'NA' },
  { code: 'ia', name: 'Interlingua' },
  { code: 'id', name: 'Indonesian', countryCode: 'ID' },
  { code: 'ie', name: 'Interlingue' },
  { code: 'ig', name: 'Igbo', countryCode: 'NG' },
  { code: 'ii', name: 'Sichuan Yi', countryCode: 'CN' },
  { code: 'ik', name: 'Inupiaq', countryCode: 'US' },
  { code: 'io', name: 'Ido' },
  { code: 'is', name: 'Icelandic', countryCode: 'IS' },
  { code: 'it', name: 'Italian', countryCode: 'IT' },
  { code: 'iu', name: 'Inuktitut', countryCode: 'CA' },
  { code: 'ja', name: 'Japanese', countryCode: 'JP' },
  { code: 'jv', name: 'Javanese', countryCode: 'ID' },
  { code: 'ka', name: 'Georgian', countryCode: 'GE' },
  { code: 'kg', name: 'Kongo', countryCode: 'CD' },
  { code: 'ki', name: 'Kikuyu', countryCode: 'KE' },
  { code: 'kj', name: 'Kuanyama', countryCode: 'NA' },
  { code: 'kk', name: 'Kazakh', countryCode: 'KZ' },
  { code: 'kl', name: 'Kalaallisut', countryCode: 'GL' },
  { code: 'km', name: 'Central Khmer', countryCode: 'KH' },
  { code: 'kn', name: 'Kannada', countryCode: 'IN' },
  { code: 'ko', name: 'Korean', countryCode: 'KR' },
  { code: 'kr', name: 'Kanuri', countryCode: 'NG' },
  { code: 'ks', name: 'Kashmiri', countryCode: 'IN' },
  { code: 'ku', name: 'Kurdish', countryCode: 'IQ' },
  { code: 'kv', name: 'Komi', countryCode: 'RU' },
  { code: 'kw', name: 'Cornish', countryCode: 'GB' },
  { code: 'ky', name: 'Kirghiz', countryCode: 'KG' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Luxembourgish', countryCode: 'LU' },
  { code: 'lg', name: 'Ganda', countryCode: 'UG' },
  { code: 'li', name: 'Limburgish', countryCode: 'NL' },
  { code: 'ln', name: 'Lingala', countryCode: 'CD' },
  { code: 'lo', name: 'Lao', countryCode: 'LA' },
  { code: 'lt', name: 'Lithuanian', countryCode: 'LT' },
  { code: 'lu', name: 'Luba-Katanga', countryCode: 'CD' },
  { code: 'lv', name: 'Latvian', countryCode: 'LV' },
  { code: 'mg', name: 'Malagasy', countryCode: 'MG' },
  { code: 'mh', name: 'Marshallese', countryCode: 'MH' },
  { code: 'mi', name: 'Maori', countryCode: 'NZ' },
  { code: 'mk', name: 'Macedonian', countryCode: 'MK' },
  { code: 'ml', name: 'Malayalam', countryCode: 'IN' },
  { code: 'mn', name: 'Mongolian', countryCode: 'MN' },
  { code: 'mr', name: 'Marathi', countryCode: 'IN' },
  { code: 'ms', name: 'Malay', countryCode: 'MY' },
  { code: 'mt', name: 'Maltese', countryCode: 'MT' },
  { code: 'my', name: 'Burmese', countryCode: 'MM' },
  { code: 'na', name: 'Nauru', countryCode: 'NR' },
  { code: 'nb', name: 'Norwegian Bokmål', countryCode: 'NO' },
  { code: 'nd', name: 'North Ndebele', countryCode: 'ZW' },
  { code: 'ne', name: 'Nepali', countryCode: 'NP' },
  { code: 'ng', name: 'Ndonga', countryCode: 'NA' },
  { code: 'nl', name: 'Dutch', countryCode: 'NL' },
  { code: 'nn', name: 'Norwegian Nynorsk', countryCode: 'NO' },
  { code: 'no', name: 'Norwegian', countryCode: 'NO' },
  { code: 'nr', name: 'South Ndebele', countryCode: 'ZA' },
  { code: 'nv', name: 'Navajo', countryCode: 'US' },
  { code: 'ny', name: 'Chichewa', countryCode: 'MW' },
  { code: 'oc', name: 'Occitan', countryCode: 'FR' },
  { code: 'oj', name: 'Ojibwe', countryCode: 'CA' },
  { code: 'om', name: 'Oromo', countryCode: 'ET' },
  { code: 'or', name: 'Oriya', countryCode: 'IN' },
  { code: 'os', name: 'Ossetian', countryCode: 'RU' },
  { code: 'pa', name: 'Panjabi', countryCode: 'IN' },
  { code: 'pi', name: 'Pali', countryCode: 'IN' },
  { code: 'pl', name: 'Polish', countryCode: 'PL' },
  { code: 'ps', name: 'Pushto', countryCode: 'AF' },
  { code: 'pt', name: 'Portuguese', countryCode: 'PT' },
  { code: 'qu', name: 'Quechua', countryCode: 'PE' },
  { code: 'rm', name: 'Romansh', countryCode: 'CH' },
  { code: 'rn', name: 'Rundi', countryCode: 'BI' },
  { code: 'ro', name: 'Romanian', countryCode: 'RO' },
  { code: 'ru', name: 'Russian', countryCode: 'RU' },
  { code: 'rw', name: 'Kinyarwanda', countryCode: 'RW' },
  { code: 'sa', name: 'Sanskrit', countryCode: 'IN' },
  { code: 'sc', name: 'Sardinian', countryCode: 'IT' },
  { code: 'sd', name: 'Sindhi', countryCode: 'PK' },
  { code: 'se', name: 'Northern Sami', countryCode: 'NO' },
  { code: 'sg', name: 'Sango', countryCode: 'CF' },
  { code: 'si', name: 'Sinhalese', countryCode: 'LK' },
  { code: 'sk', name: 'Slovak', countryCode: 'SK' },
  { code: 'sl', name: 'Slovenian', countryCode: 'SI' },
  { code: 'sm', name: 'Samoan', countryCode: 'WS' },
  { code: 'sn', name: 'Shona', countryCode: 'ZW' },
  { code: 'so', name: 'Somali', countryCode: 'SO' },
  { code: 'sq', name: 'Albanian', countryCode: 'AL' },
  { code: 'sr', name: 'Serbian', countryCode: 'RS' },
  { code: 'ss', name: 'Swati', countryCode: 'SZ' },
  { code: 'st', name: 'Sotho, Southern', countryCode: 'LS' },
  { code: 'su', name: 'Sundanese', countryCode: 'ID' },
  { code: 'sv', name: 'Swedish', countryCode: 'SE' },
  { code: 'sw', name: 'Swahili', countryCode: 'KE' },
  { code: 'ta', name: 'Tamil', countryCode: 'IN' },
  { code: 'te', name: 'Telugu', countryCode: 'IN' },
  { code: 'tg', name: 'Tajik', countryCode: 'TJ' },
  { code: 'th', name: 'Thai', countryCode: 'TH' },
  { code: 'ti', name: 'Tigrinya', countryCode: 'ER' },
  { code: 'tk', name: 'Turkmen', countryCode: 'TM' },
  { code: 'tl', name: 'Tagalog', countryCode: 'PH' },
  { code: 'tn', name: 'Tswana', countryCode: 'BW' },
  { code: 'to', name: 'Tonga', countryCode: 'TO' },
  { code: 'tr', name: 'Turkish', countryCode: 'TR' },
  { code: 'ts', name: 'Tsonga', countryCode: 'ZA' },
  { code: 'tt', name: 'Tatar', countryCode: 'RU' },
  { code: 'tw', name: 'Twi', countryCode: 'GH' },
  { code: 'ty', name: 'Tahitian', countryCode: 'PF' },
  { code: 'ug', name: 'Uighur', countryCode: 'CN' },
  { code: 'uk', name: 'Ukrainian', countryCode: 'UA' },
  { code: 'ur', name: 'Urdu', countryCode: 'PK' },
  { code: 'uz', name: 'Uzbek', countryCode: 'UZ' },
  { code: 've', name: 'Venda', countryCode: 'ZA' },
  { code: 'vi', name: 'Vietnamese', countryCode: 'VN' },
  { code: 'vo', name: 'Volapük' },
  { code: 'wa', name: 'Walloon', countryCode: 'BE' },
  { code: 'wo', name: 'Wolof', countryCode: 'SN' },
  { code: 'xh', name: 'Xhosa', countryCode: 'ZA' },
  { code: 'yi', name: 'Yiddish', countryCode: 'IL' },
  { code: 'yo', name: 'Yoruba', countryCode: 'NG' },
  { code: 'za', name: 'Zhuang', countryCode: 'CN' },
  { code: 'zh', name: 'Chinese', countryCode: 'CN' },
  { code: 'zu', name: 'Zulu', countryCode: 'ZA' },
]
